name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        apt-get install build-essential
        apt-get install libasound-dev or libasound2-dev
        apt-get install libjack0
        apt-get install libjack-dev
        apt-get install python-pip
        apt-get install python-dev
        pip install python-rtmidi
        # pip install python-rtmidi --install-option="--no-jack"
        # pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
